dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: JgRtqn94w9JjGsfkZ7QWMUlB41rqMw/YOP4VsXAF1c9//mH4vjf7EiOvtqGmExfM1tEclA3MKh22vIN6vo74RlpX7vVXyMbGgqQj9HNS+GKz7Z2HLZXWL2IPhrVuWtj/RaYc/bBPVSTAJsxl5YNedJdUGrKAgLpWX2KPeCxuH3jwblt45AB3uo3SyZHXvi2ez0d/Q4jcA3fhVKcj0C8RKfMKokAIcPQeDAxCRI53bbAuDYvAzZZLOv+70x0Jy7ehVDeFmka/ZQblQfuM3U6cwvHvNnNWxFunlTTbKwMuOERM9DS29fqUJ+TAzKEgihKe18GzluTQQwXfGOK8HJ5Dr28fU50zvqS2079W8V5HfsL07UdLB0phU8aDKS4bBGzTqrZSa3pCsp1TLSxEE68qRGqxjI/8uEiFjtuqWaxnltICIbzRUqVj63pdINmesAAX7T4t0abQtvkwdhwhVcmTn0CmEQoa7ACsG5TXYuj2HoELzgYiu/78ck6m3UpIk2fF6rK5Xy0toZKURsFjS2sjXgW4Udy2U905OYmIVLk7Wpk7mzJOZgW/+G73al1iBqEJmFvCNqP2LPPNhE83u4Te8n+on4yip8ia5MUK42xBJ3oTC+IvgnFR9KiyB/Y2q7qMWEBJGtj23zYIV3tRXklAFoSZ4Ub2cn9s+A99XiMdh2o=
  - secure: Ddb+bBJWACHfemhW24t9IRuec1y28hpEzao6dsBvbff93L8JxGz3YIJPzpcKobFvFPeGayzhI73bD/9K/vZkl2GD1cDgttwqX0MuXDO1kLbM2BjMtit73JWYXfbw33LJ4OMt5mhb9xrUjqxsnuXX/uzlbiwWoPIQ1Km9uwAldnSc8NK8dGy+TzCJyeC6TC0RO2ZOPX1G6rBTHc2KmiQC7P/mxZjKMt3iNZstt1cNxKSbQ00O3yzcpkAAL1Gw6zGk8m52cUlJ6BT9t2uHwsGgE5ds7eb/rH6U/OwY1+noWt4XhnvFwkQcXzac1CxhmATAmKiNBno57tEW297KmMlXoz3yi6wLASmcX0aBUV0jtIeC9sWy5vb0Z4ptO0IpUVlIyedHmd9KH2n9oXsFP8XdXNU5/T7X+JSVgovGD9ryed2p7aXLze8iUR7e33g6Kv+JmFaL92nJOGEM94/SQ80LH8T+JuFtTUK5lMqQrqZKn428X2w4ZrZmpQxw7gVi25SmlAwuk0L9BJ/NvNUwKxBXcskFXe4CjHVZHaJh9fzvwnDLKfYL1uh5fEeBcPMnnzXW2fmxJDx9pG58M+tULC7SuNKWnN6k/CPwteBqS2qq8s7xDpn66Q3EL4KPU6F77stQ9XwaRZtOaNj5Jc4VYTFWv/0G//7Cg+i6MbaSQ4S6/Bo=
  - secure: brf4Z+SV9RiZA4AlQ8MeX2s32snTBtN0r3m1QeH7FhZRGo57Ha4vD+K6LAhkXC4sVqE1HpeocHcqAGzcusOyQ5qzqSQvtw3CyDKDDve7x1dt3axLu694oeaz2J2F3xtixRPjyCE/5oML3roZZ/boQDJ4cVfvoeR/N4uwKGXjn7h+a1lLrC+C3itLVsqK47ZDUTvAMlglcZUmSWVeRs4/upEmo92DXj/QODU8G87dtTFvcA2ZunQD6R9gd75Ye4lyL6dnhlVeXt96GFWtd/+KOLrkXslhgkG57/4TwGOPTeDa/KzHvDjy5nb5WeFfzx7HtIgd1TA1X0uxyAr/0BP8ueaK7NJW8SqrfgZn1o6fWmCmiZIK439wMG8aPNoswrnQKGMqvBkK1tG9/+t0jX9+SWKHtRNF4B4uykAprxgLEefFk106+Zb3stnzSEI2Zkb0iAjE5K5MPwK1BzNPJsePcCiYvXEN+CfnouUxIlPzvRPCIc7kvnGmfN8I8IamU9pyCZ/HXrQzcAitYJH+61O4fSPZ5349kWT9zNYr5XclZjTB9oRVdZhd4U9vrqeY/l3sFxF8XfYnbs/xDCnJKNKjfpsWr5F1/LcG1nLjLxzId7w9NGmodJPTQv1sA/upMKwHLSa+NFhey/DweaKV9xcsgBMHx+JPtJ9x+gwVPL2uUdQ=
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
install: true
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.atomist"
