dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: JteB0uJ+CNGETj+WZ39As4p5Dld1obA5DfabBc8/2bsHVViuoLb9r/2NqcsUodyX+2kMnDAqCzA1iImD4fnDz1fWerig/2lDS5FWiqg3NFuIcRUnfHmwXqX1UtkscDuR/BAiYLUK7HmMGKnNaUYyQaFhJhdQ8tPpQVCdBszHW2vCQWvLYxIbMcFIfK2VHk3gp41xuoa5Irg23X5008GrcKodz0OGpuA8av+SroC44hXLysy5JPfQqv+GOgvuYODFjMsmKVHLPNki2N3GzYy3Wt46QcGlLA5oScpTnAD6E0QAhXW4q+De+ZuWtNzEkmZy6HQN/sgKqM6EXtC3pozL4Nh1g7xaS/wUi/03s1UxrnAO21AqeNA8Ggny7zy97SfS/Ru8v1e0HVVvoTQubkQrDDCh6gt1uQ9wzm/wJzyw+rHd/CTwF7IZ0IY93UQLQUT50290/toA4WNDB7fDoFvAkzHFLWSyTBNwxiiII0th4lL3VTfBRqUN68LIiN30w84IBIqQiSCq8yc/ApEuDTv0sI+LvT1crMzVU+yM3AhEdeQy+Aw5lMI4s2H6R7xg+0vzwuDt42Pfv+jgmfhvLWLPDI2qEvjx75bMBC8my60U4uWqvWY0fhZ645sFXGNvXICW+A7YUeQScgTZAi2Dyy4+74cm7QUB8NJ0mPupcGwmyKM=
  - secure: RXAtOHf69JllbsOpcwrtCzrPxTKhUih7ztBTZRe7AaoQDMjzjqlh2aLWvuxIqfvmLd7QcBpvxsaPl/nNG+/TOqkVASPNQTkFG542cYtjZBE7xN74PNVPAHpeMsxMRWXtM8Cc+fM2iO4TApmT73V+RTi8tfcTNltLQOwSjbjaKSGvKP8d+cfP029+ywuM5U6otOTbfVGNT1/bh2Un6fPx1JXDwhcOywne9J1PKlR96v+5D1Z8Eo9VwfqAbx5cOM80I1YmHdKlM5m8tkiWmfryAGsa2f4DgDFba267bi5/AEWt3s29LuIMDPfHJNgmVAotSB6iYt7scv7pud41HyvtMbP7iotAsTEabZkxGQE1nHEYDhsqQTjDGeMi4cGiNmbSJDopGpE3CBPSzwno+6S9sZSZXogGAEhqFZQhuyjUF2kST9NxudCg72Uza/rllV5NeXyuyNzKJ06Iym2fvj9FmHoO9am7uwWCuTC7u3r4sO8ArWVVIpXcCZYDzV7uBZporIHSumnehEB0XQoIWeYvn3T38yTLJycQrvfRtq/r7OAjHmgw0tG2Gs1JYgsGnZgANanz6iouTvOt+HLusFIgObX3lHTGEIAkr540sy9FuxoRmCjSYfEW7DGrKULJLJHzPwGhajED05x3BuR5XxEMXzQap+02tUZY3O98sodC448=
  - secure: I3YYdiP5IONamkfqBoftj9LDLjdNyltmHg1yYPXsXL4yQFop9JPOcwZPTuYU/sm83wKuZRTyw3Uv7Bvp5sCo0NE3LKtJrcFNTeyCUVVF/mueYnY1OoX1Kg9RJUhOuqw5auXFMqzjyep2R/tGEqBbCLg0yNTqYoUSFWAt+NMo2zQyHRJtTOMO3Ta3eRu8HsJlDQwthS0gtr+x13CNUuodfeqsmCIbfTZ/sP2At2A+ns27Umx2m47px8OPLTLR2CpUuQQM6A/dzutZnPS2l/bVi0LoniYvHOfbwhQh/KQ7QXgHhC7aBVZnQpur00TJxX/rLFrPpL/Y4w3XbN6eshcX6FlNW1LV2KP6S8BFvzL2OBkd5s02JeRI7mdW0FO1qBw0x00BArvn2rtklh3wlrLNJNw8S5mu0Spsna2C5Sf1kAq3iZvvyfTJaWH0FxkQwMk3UX5E7Xu93cpC9BsTsVfZF2onUI6U1eGXxvkGXUFR+PJ4Lr0PtSC5UqzbCtd0Ru4BRE1VqWFEDpMcqu9O0oLAs5XH+F8XuGUveUx6r5762VlfUZgok/4tzhN6knjP1nxiN0bNBInhT/NkpTw6DXIG0HjoIOM8yPE4PQoOjXDkriie5VCQoaowcz2GXd1jQGXQDu09SXzU3dAaFZojwf3+0op4aztIukO0bBM9uYa4RJU=
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
install: true
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.atomist"
